CREATE TABLE IF EXISTS USERS(
    UserID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    UserName VARCHAR(50) UNIQUE, 
    RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF EXISTS COMMENTS (
	CommentID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    UserID INT NOT NULL,
    Comment TEXT NOT NULL, 
    PostDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE
);

CREATE TABLE IF EXISTS Rating(
	RatingID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    Rating INT NOT NULL, 
    PostDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    UserID INT NOT NULL, 
    CommentID INT NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CommentID) REFERENCES COMMENTS(CommentID) ON DELETE CASCADE
);