CREATE TABLE IF NOT EXISTS USERS(
    UserID INTEGER PRIMARY KEY AUTOINCREMENT , 
    UserName TEXT UNIQUE, 
    RegistrationDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMMENTS (
	CommentID INTEGER PRIMARY KEY AUTOINCREMENT ,
    UserID INTEGER NOT NULL,
    Comment TEXT NOT NULL, 
    PostDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Rating(
	RatingID INTEGER PRIMARY KEY AUTOINCREMENT , 
    Rating INTEGER NOT NULL, 
    PostDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    UserID INTEGER NOT NULL, 
    CommentID INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CommentID) REFERENCES COMMENTS(CommentID) ON DELETE CASCADE
);