CREATE TABLE IF NOT EXISTS USERS(
	UserID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    UserName VARCHAR(50) UNIQUE NOT NULL, 
    RegistrationDate DATE
);

CREATE TABLE IF NOT EXISTS COMMENTS (
	CommentID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    UserID INT NOT NULL,
    Comment TEXT NOT NULL, 
    PostDate DATE,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Rating(
	RatingID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE, 
    Rating INT NOT NULL, 
    PostDate DATE,
    UserID INT NOT NULL, 
    CommentID INT NOT NULL UNIQUE,
    FOREIGN KEY (UserID) REFERENCES USERS(UserID) ON DELETE CASCADE,
    FOREIGN KEY (CommentID) REFERENCES COMMENTS(CommentID) ON DELETE CASCADE
);